name: entidb
description: An embedded, entity-based document database for Dart and Flutter with typed collections, indexing, transactions, encryption, and backup support.
version: 1.0.1
repository: https://github.com/Tembocs/entidb

environment:
  sdk: ^3.10.1

# Add regular dependencies here.
dependencies:
  bcrypt: ^1.1.3
  cbor: ^6.3.7
  crypto: ^3.0.7
  cryptography: ^2.7.0
  dart_jsonwebtoken: ">=2.16.0 <4.0.0"
  logging: ^1.3.0
  meta: ^1.16.0
  path: ^1.9.0
  synchronized: ^3.4.0
  uuid: ^4.5.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
