name: docdb
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.1

# Add regular dependencies here.
dependencies:
  bcrypt: ^1.1.3
  crypto: ^3.0.7
  cryptography: ^2.7.0
  dart_jsonwebtoken: ^2.16.0
  logging: ^1.3.0
  meta: ^1.16.0
  synchronized: ^3.4.0
  uuid: ^4.5.2
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
